### ISSUE TITLE
Check for existing logged in users on start

### ISSUE THREAD

**Issue by Lim-Hong-Ying** [Lim-Hong-Ying/MAD-P03-Group-GG#91]
Adding a check for logged in user during splash screen, and skipping login process if user is present can enhance usage experience.

**Comment by DancinComrade** [comment]
Can refer to this
https://stackoverflow.com/questions/22262463/firebase-how-to-keep-an-android-user-logged-in
https://stackoverflow.com/questions/33943661/how-to-keep-a-user-persistent-logged-in-through-my-android-application-with-fire
