### ISSUE TITLE
Fix RecyclerView viewholders when user scrolls quickly

### ISSUE THREAD

**Issue by Lim-Hong-Ying** [Lim-Hong-Ying/MAD-P03-Group-GG#95]
Fix viewholders by resetting viewholders whenever image is not downloaded yet. Setting the viewholder as GONE before image is downloaded, or by resetting viewholder for every new image.

**Comment by DancinComrade** [comment]
I think can use FirebaseRecyclerAdapter, i use edi seems to have no problem, but not too sure
